/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthedAnalyzeRouteImport } from './routes/_authed/analyze'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'
import { Route as AuthedDocumentsRouteImport } from './routes/_authed/documents'
import { Route as AuthedHelpRouteImport } from './routes/_authed/help'
import { Route as AuthedSetupRouteImport } from './routes/_authed/setup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminEftRouteImport } from './routes/admin/eft'
import { Route as AdminHelpRouteImport } from './routes/admin/help'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAdminCompaniesRouteImport } from './routes/api/admin/companies'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingPackagesRouteImport } from './routes/api/billing/packages'
import { Route as ApiCompaniesIndexRouteImport } from './routes/api/companies/index'
import { Route as ApiCompaniesCompanyIdRouteImport } from './routes/api/companies/$companyId'
import { Route as ApiDashboardActivityRouteImport } from './routes/api/dashboard/activity'
import { Route as ApiDocumentsIdRouteImport } from './routes/api/documents/$id'
import { Route as ApiDocumentsPreviewBbbeeRouteImport } from './routes/api/documents/preview-bbbee'
import { Route as ApiDocumentsUploadRouteImport } from './routes/api/documents/upload'
import { Route as ApiEftBankDetailsRouteImport } from './routes/api/eft/bank-details'
import { Route as ApiEftMyRequestsRouteImport } from './routes/api/eft/my-requests'
import { Route as ApiEftRequestRouteImport } from './routes/api/eft/request'
import { Route as ApiReferenceBargainingCouncilsRouteImport } from './routes/api/reference/bargaining-councils'
import { Route as ApiReferralsLookupRouteImport } from './routes/api/referrals/lookup'
import { Route as ApiReferralsMyRouteImport } from './routes/api/referrals/my'
import { Route as ApiRemindersSweepRouteImport } from './routes/api/reminders/sweep'
import { Route as ApiTenderTenderIdRouteImport } from './routes/api/tender/$tenderId'
import { Route as ApiTendersCompanyIdRouteImport } from './routes/api/tenders/$companyId'
import { Route as ApiTendersAnalyzeRouteImport } from './routes/api/tenders/analyze'
import { Route as ApiVerifyStatutoryRouteImport } from './routes/api/verify/statutory'
import { Route as ApiAdminCompaniesCompanyIdRouteImport } from './routes/api/admin/companies/$companyId'
import { Route as ApiAdminImpersonateUserIdRouteImport } from './routes/api/admin/impersonate/$userId'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users/$userId'
import { Route as ApiBillingCreditsCompanyIdRouteImport } from './routes/api/billing/credits/$companyId'
import { Route as ApiDocumentsCompanyCompanyIdRouteImport } from './routes/api/documents/company/$companyId'
import { Route as ApiDocumentsDownloadDocIdRouteImport } from './routes/api/documents/download/$docId'
import { Route as ApiEftAdminAllRouteImport } from './routes/api/eft/admin/all'
import { Route as ApiEftRequestPaymentIdRouteImport } from './routes/api/eft/request/$paymentId'
import { Route as ApiEftUploadProofPaymentIdRouteImport } from './routes/api/eft/upload-proof/$paymentId'
import { Route as ApiRemindersTestCompanyIdRouteImport } from './routes/api/reminders/test/$companyId'
import { Route as ApiTenderTenderIdSbd4RouteImport } from './routes/api/tender/$tenderId/sbd4'
import { Route as ApiTenderTenderIdSbd61RouteImport } from './routes/api/tender/$tenderId/sbd61'
import { Route as ApiTendersDownloadTenderIdRouteImport } from './routes/api/tenders/download/$tenderId'
import { Route as ApiEftAdminPaymentIdConfirmRouteImport } from './routes/api/eft/admin/$paymentId/confirm'
import { Route as ApiEftAdminPaymentIdRejectRouteImport } from './routes/api/eft/admin/$paymentId/reject'
import { Route as ApiEftAdminProofPaymentIdRouteImport } from './routes/api/eft/admin/proof/$paymentId'
import { Route as ApiTenderTenderIdReturnablesToggleRouteImport } from './routes/api/tender/$tenderId/returnables/toggle'
import { Route as ApiTenderTenderIdReturnablesUploadRouteImport } from './routes/api/tender/$tenderId/returnables/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAnalyzeRoute = AuthedAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDocumentsRoute = AuthedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHelpRoute = AuthedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSetupRoute = AuthedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEftRoute = AdminEftRouteImport.update({
  id: '/eft',
  path: '/eft',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAdminCompaniesRoute = ApiAdminCompaniesRouteImport.update({
  id: '/api/admin/companies',
  path: '/api/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPackagesRoute = ApiBillingPackagesRouteImport.update({
  id: '/api/billing/packages',
  path: '/api/billing/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesIndexRoute = ApiCompaniesIndexRouteImport.update({
  id: '/api/companies/',
  path: '/api/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesCompanyIdRoute = ApiCompaniesCompanyIdRouteImport.update({
  id: '/api/companies/$companyId',
  path: '/api/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardActivityRoute = ApiDashboardActivityRouteImport.update({
  id: '/api/dashboard/activity',
  path: '/api/dashboard/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsIdRoute = ApiDocumentsIdRouteImport.update({
  id: '/api/documents/$id',
  path: '/api/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsPreviewBbbeeRoute =
  ApiDocumentsPreviewBbbeeRouteImport.update({
    id: '/api/documents/preview-bbbee',
    path: '/api/documents/preview-bbbee',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsUploadRoute = ApiDocumentsUploadRouteImport.update({
  id: '/api/documents/upload',
  path: '/api/documents/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEftBankDetailsRoute = ApiEftBankDetailsRouteImport.update({
  id: '/api/eft/bank-details',
  path: '/api/eft/bank-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEftMyRequestsRoute = ApiEftMyRequestsRouteImport.update({
  id: '/api/eft/my-requests',
  path: '/api/eft/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEftRequestRoute = ApiEftRequestRouteImport.update({
  id: '/api/eft/request',
  path: '/api/eft/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceBargainingCouncilsRoute =
  ApiReferenceBargainingCouncilsRouteImport.update({
    id: '/api/reference/bargaining-councils',
    path: '/api/reference/bargaining-councils',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReferralsLookupRoute = ApiReferralsLookupRouteImport.update({
  id: '/api/referrals/lookup',
  path: '/api/referrals/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsMyRoute = ApiReferralsMyRouteImport.update({
  id: '/api/referrals/my',
  path: '/api/referrals/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindersSweepRoute = ApiRemindersSweepRouteImport.update({
  id: '/api/reminders/sweep',
  path: '/api/reminders/sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTenderTenderIdRoute = ApiTenderTenderIdRouteImport.update({
  id: '/api/tender/$tenderId',
  path: '/api/tender/$tenderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTendersCompanyIdRoute = ApiTendersCompanyIdRouteImport.update({
  id: '/api/tenders/$companyId',
  path: '/api/tenders/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTendersAnalyzeRoute = ApiTendersAnalyzeRouteImport.update({
  id: '/api/tenders/analyze',
  path: '/api/tenders/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyStatutoryRoute = ApiVerifyStatutoryRouteImport.update({
  id: '/api/verify/statutory',
  path: '/api/verify/statutory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCompaniesCompanyIdRoute =
  ApiAdminCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => ApiAdminCompaniesRoute,
  } as any)
const ApiAdminImpersonateUserIdRoute =
  ApiAdminImpersonateUserIdRouteImport.update({
    id: '/api/admin/impersonate/$userId',
    path: '/api/admin/impersonate/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiBillingCreditsCompanyIdRoute =
  ApiBillingCreditsCompanyIdRouteImport.update({
    id: '/api/billing/credits/$companyId',
    path: '/api/billing/credits/$companyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsCompanyCompanyIdRoute =
  ApiDocumentsCompanyCompanyIdRouteImport.update({
    id: '/api/documents/company/$companyId',
    path: '/api/documents/company/$companyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsDownloadDocIdRoute =
  ApiDocumentsDownloadDocIdRouteImport.update({
    id: '/api/documents/download/$docId',
    path: '/api/documents/download/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEftAdminAllRoute = ApiEftAdminAllRouteImport.update({
  id: '/api/eft/admin/all',
  path: '/api/eft/admin/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEftRequestPaymentIdRoute = ApiEftRequestPaymentIdRouteImport.update({
  id: '/$paymentId',
  path: '/$paymentId',
  getParentRoute: () => ApiEftRequestRoute,
} as any)
const ApiEftUploadProofPaymentIdRoute =
  ApiEftUploadProofPaymentIdRouteImport.update({
    id: '/api/eft/upload-proof/$paymentId',
    path: '/api/eft/upload-proof/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRemindersTestCompanyIdRoute =
  ApiRemindersTestCompanyIdRouteImport.update({
    id: '/api/reminders/test/$companyId',
    path: '/api/reminders/test/$companyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTenderTenderIdSbd4Route = ApiTenderTenderIdSbd4RouteImport.update({
  id: '/sbd4',
  path: '/sbd4',
  getParentRoute: () => ApiTenderTenderIdRoute,
} as any)
const ApiTenderTenderIdSbd61Route = ApiTenderTenderIdSbd61RouteImport.update({
  id: '/sbd61',
  path: '/sbd61',
  getParentRoute: () => ApiTenderTenderIdRoute,
} as any)
const ApiTendersDownloadTenderIdRoute =
  ApiTendersDownloadTenderIdRouteImport.update({
    id: '/api/tenders/download/$tenderId',
    path: '/api/tenders/download/$tenderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEftAdminPaymentIdConfirmRoute =
  ApiEftAdminPaymentIdConfirmRouteImport.update({
    id: '/api/eft/admin/$paymentId/confirm',
    path: '/api/eft/admin/$paymentId/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEftAdminPaymentIdRejectRoute =
  ApiEftAdminPaymentIdRejectRouteImport.update({
    id: '/api/eft/admin/$paymentId/reject',
    path: '/api/eft/admin/$paymentId/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEftAdminProofPaymentIdRoute =
  ApiEftAdminProofPaymentIdRouteImport.update({
    id: '/api/eft/admin/proof/$paymentId',
    path: '/api/eft/admin/proof/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTenderTenderIdReturnablesToggleRoute =
  ApiTenderTenderIdReturnablesToggleRouteImport.update({
    id: '/returnables/toggle',
    path: '/returnables/toggle',
    getParentRoute: () => ApiTenderTenderIdRoute,
  } as any)
const ApiTenderTenderIdReturnablesUploadRoute =
  ApiTenderTenderIdReturnablesUploadRouteImport.update({
    id: '/returnables/upload',
    path: '/returnables/upload',
    getParentRoute: () => ApiTenderTenderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/analyze': typeof AuthedAnalyzeRoute
  '/app': typeof AuthedAppRoute
  '/billing': typeof AuthedBillingRoute
  '/documents': typeof AuthedDocumentsRoute
  '/help': typeof AuthedHelpRoute
  '/setup': typeof AuthedSetupRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/eft': typeof AdminEftRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/companies': typeof ApiAdminCompaniesRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/packages': typeof ApiBillingPackagesRoute
  '/api/companies/$companyId': typeof ApiCompaniesCompanyIdRoute
  '/api/dashboard/activity': typeof ApiDashboardActivityRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/documents/preview-bbbee': typeof ApiDocumentsPreviewBbbeeRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/eft/bank-details': typeof ApiEftBankDetailsRoute
  '/api/eft/my-requests': typeof ApiEftMyRequestsRoute
  '/api/eft/request': typeof ApiEftRequestRouteWithChildren
  '/api/reference/bargaining-councils': typeof ApiReferenceBargainingCouncilsRoute
  '/api/referrals/lookup': typeof ApiReferralsLookupRoute
  '/api/referrals/my': typeof ApiReferralsMyRoute
  '/api/reminders/sweep': typeof ApiRemindersSweepRoute
  '/api/tender/$tenderId': typeof ApiTenderTenderIdRouteWithChildren
  '/api/tenders/$companyId': typeof ApiTendersCompanyIdRoute
  '/api/tenders/analyze': typeof ApiTendersAnalyzeRoute
  '/api/verify/statutory': typeof ApiVerifyStatutoryRoute
  '/api/companies/': typeof ApiCompaniesIndexRoute
  '/api/admin/companies/$companyId': typeof ApiAdminCompaniesCompanyIdRoute
  '/api/admin/impersonate/$userId': typeof ApiAdminImpersonateUserIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/billing/credits/$companyId': typeof ApiBillingCreditsCompanyIdRoute
  '/api/documents/company/$companyId': typeof ApiDocumentsCompanyCompanyIdRoute
  '/api/documents/download/$docId': typeof ApiDocumentsDownloadDocIdRoute
  '/api/eft/admin/all': typeof ApiEftAdminAllRoute
  '/api/eft/request/$paymentId': typeof ApiEftRequestPaymentIdRoute
  '/api/eft/upload-proof/$paymentId': typeof ApiEftUploadProofPaymentIdRoute
  '/api/reminders/test/$companyId': typeof ApiRemindersTestCompanyIdRoute
  '/api/tender/$tenderId/sbd4': typeof ApiTenderTenderIdSbd4Route
  '/api/tender/$tenderId/sbd61': typeof ApiTenderTenderIdSbd61Route
  '/api/tenders/download/$tenderId': typeof ApiTendersDownloadTenderIdRoute
  '/api/eft/admin/$paymentId/confirm': typeof ApiEftAdminPaymentIdConfirmRoute
  '/api/eft/admin/$paymentId/reject': typeof ApiEftAdminPaymentIdRejectRoute
  '/api/eft/admin/proof/$paymentId': typeof ApiEftAdminProofPaymentIdRoute
  '/api/tender/$tenderId/returnables/toggle': typeof ApiTenderTenderIdReturnablesToggleRoute
  '/api/tender/$tenderId/returnables/upload': typeof ApiTenderTenderIdReturnablesUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/analyze': typeof AuthedAnalyzeRoute
  '/app': typeof AuthedAppRoute
  '/billing': typeof AuthedBillingRoute
  '/documents': typeof AuthedDocumentsRoute
  '/help': typeof AuthedHelpRoute
  '/setup': typeof AuthedSetupRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/eft': typeof AdminEftRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/companies': typeof ApiAdminCompaniesRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/packages': typeof ApiBillingPackagesRoute
  '/api/companies/$companyId': typeof ApiCompaniesCompanyIdRoute
  '/api/dashboard/activity': typeof ApiDashboardActivityRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/documents/preview-bbbee': typeof ApiDocumentsPreviewBbbeeRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/eft/bank-details': typeof ApiEftBankDetailsRoute
  '/api/eft/my-requests': typeof ApiEftMyRequestsRoute
  '/api/eft/request': typeof ApiEftRequestRouteWithChildren
  '/api/reference/bargaining-councils': typeof ApiReferenceBargainingCouncilsRoute
  '/api/referrals/lookup': typeof ApiReferralsLookupRoute
  '/api/referrals/my': typeof ApiReferralsMyRoute
  '/api/reminders/sweep': typeof ApiRemindersSweepRoute
  '/api/tender/$tenderId': typeof ApiTenderTenderIdRouteWithChildren
  '/api/tenders/$companyId': typeof ApiTendersCompanyIdRoute
  '/api/tenders/analyze': typeof ApiTendersAnalyzeRoute
  '/api/verify/statutory': typeof ApiVerifyStatutoryRoute
  '/api/companies': typeof ApiCompaniesIndexRoute
  '/api/admin/companies/$companyId': typeof ApiAdminCompaniesCompanyIdRoute
  '/api/admin/impersonate/$userId': typeof ApiAdminImpersonateUserIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/billing/credits/$companyId': typeof ApiBillingCreditsCompanyIdRoute
  '/api/documents/company/$companyId': typeof ApiDocumentsCompanyCompanyIdRoute
  '/api/documents/download/$docId': typeof ApiDocumentsDownloadDocIdRoute
  '/api/eft/admin/all': typeof ApiEftAdminAllRoute
  '/api/eft/request/$paymentId': typeof ApiEftRequestPaymentIdRoute
  '/api/eft/upload-proof/$paymentId': typeof ApiEftUploadProofPaymentIdRoute
  '/api/reminders/test/$companyId': typeof ApiRemindersTestCompanyIdRoute
  '/api/tender/$tenderId/sbd4': typeof ApiTenderTenderIdSbd4Route
  '/api/tender/$tenderId/sbd61': typeof ApiTenderTenderIdSbd61Route
  '/api/tenders/download/$tenderId': typeof ApiTendersDownloadTenderIdRoute
  '/api/eft/admin/$paymentId/confirm': typeof ApiEftAdminPaymentIdConfirmRoute
  '/api/eft/admin/$paymentId/reject': typeof ApiEftAdminPaymentIdRejectRoute
  '/api/eft/admin/proof/$paymentId': typeof ApiEftAdminProofPaymentIdRoute
  '/api/tender/$tenderId/returnables/toggle': typeof ApiTenderTenderIdReturnablesToggleRoute
  '/api/tender/$tenderId/returnables/upload': typeof ApiTenderTenderIdReturnablesUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authed/analyze': typeof AuthedAnalyzeRoute
  '/_authed/app': typeof AuthedAppRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/documents': typeof AuthedDocumentsRoute
  '/_authed/help': typeof AuthedHelpRoute
  '/_authed/setup': typeof AuthedSetupRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/eft': typeof AdminEftRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/companies': typeof ApiAdminCompaniesRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/packages': typeof ApiBillingPackagesRoute
  '/api/companies/$companyId': typeof ApiCompaniesCompanyIdRoute
  '/api/dashboard/activity': typeof ApiDashboardActivityRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/documents/preview-bbbee': typeof ApiDocumentsPreviewBbbeeRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/eft/bank-details': typeof ApiEftBankDetailsRoute
  '/api/eft/my-requests': typeof ApiEftMyRequestsRoute
  '/api/eft/request': typeof ApiEftRequestRouteWithChildren
  '/api/reference/bargaining-councils': typeof ApiReferenceBargainingCouncilsRoute
  '/api/referrals/lookup': typeof ApiReferralsLookupRoute
  '/api/referrals/my': typeof ApiReferralsMyRoute
  '/api/reminders/sweep': typeof ApiRemindersSweepRoute
  '/api/tender/$tenderId': typeof ApiTenderTenderIdRouteWithChildren
  '/api/tenders/$companyId': typeof ApiTendersCompanyIdRoute
  '/api/tenders/analyze': typeof ApiTendersAnalyzeRoute
  '/api/verify/statutory': typeof ApiVerifyStatutoryRoute
  '/api/companies/': typeof ApiCompaniesIndexRoute
  '/api/admin/companies/$companyId': typeof ApiAdminCompaniesCompanyIdRoute
  '/api/admin/impersonate/$userId': typeof ApiAdminImpersonateUserIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/billing/credits/$companyId': typeof ApiBillingCreditsCompanyIdRoute
  '/api/documents/company/$companyId': typeof ApiDocumentsCompanyCompanyIdRoute
  '/api/documents/download/$docId': typeof ApiDocumentsDownloadDocIdRoute
  '/api/eft/admin/all': typeof ApiEftAdminAllRoute
  '/api/eft/request/$paymentId': typeof ApiEftRequestPaymentIdRoute
  '/api/eft/upload-proof/$paymentId': typeof ApiEftUploadProofPaymentIdRoute
  '/api/reminders/test/$companyId': typeof ApiRemindersTestCompanyIdRoute
  '/api/tender/$tenderId/sbd4': typeof ApiTenderTenderIdSbd4Route
  '/api/tender/$tenderId/sbd61': typeof ApiTenderTenderIdSbd61Route
  '/api/tenders/download/$tenderId': typeof ApiTendersDownloadTenderIdRoute
  '/api/eft/admin/$paymentId/confirm': typeof ApiEftAdminPaymentIdConfirmRoute
  '/api/eft/admin/$paymentId/reject': typeof ApiEftAdminPaymentIdRejectRoute
  '/api/eft/admin/proof/$paymentId': typeof ApiEftAdminProofPaymentIdRoute
  '/api/tender/$tenderId/returnables/toggle': typeof ApiTenderTenderIdReturnablesToggleRoute
  '/api/tender/$tenderId/returnables/upload': typeof ApiTenderTenderIdReturnablesUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/analyze'
    | '/app'
    | '/billing'
    | '/documents'
    | '/help'
    | '/setup'
    | '/admin/companies'
    | '/admin/eft'
    | '/admin/help'
    | '/admin/users'
    | '/admin/'
    | '/api/admin/companies'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/billing/packages'
    | '/api/companies/$companyId'
    | '/api/dashboard/activity'
    | '/api/documents/$id'
    | '/api/documents/preview-bbbee'
    | '/api/documents/upload'
    | '/api/eft/bank-details'
    | '/api/eft/my-requests'
    | '/api/eft/request'
    | '/api/reference/bargaining-councils'
    | '/api/referrals/lookup'
    | '/api/referrals/my'
    | '/api/reminders/sweep'
    | '/api/tender/$tenderId'
    | '/api/tenders/$companyId'
    | '/api/tenders/analyze'
    | '/api/verify/statutory'
    | '/api/companies/'
    | '/api/admin/companies/$companyId'
    | '/api/admin/impersonate/$userId'
    | '/api/admin/users/$userId'
    | '/api/billing/credits/$companyId'
    | '/api/documents/company/$companyId'
    | '/api/documents/download/$docId'
    | '/api/eft/admin/all'
    | '/api/eft/request/$paymentId'
    | '/api/eft/upload-proof/$paymentId'
    | '/api/reminders/test/$companyId'
    | '/api/tender/$tenderId/sbd4'
    | '/api/tender/$tenderId/sbd61'
    | '/api/tenders/download/$tenderId'
    | '/api/eft/admin/$paymentId/confirm'
    | '/api/eft/admin/$paymentId/reject'
    | '/api/eft/admin/proof/$paymentId'
    | '/api/tender/$tenderId/returnables/toggle'
    | '/api/tender/$tenderId/returnables/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/analyze'
    | '/app'
    | '/billing'
    | '/documents'
    | '/help'
    | '/setup'
    | '/admin/companies'
    | '/admin/eft'
    | '/admin/help'
    | '/admin/users'
    | '/admin'
    | '/api/admin/companies'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/billing/packages'
    | '/api/companies/$companyId'
    | '/api/dashboard/activity'
    | '/api/documents/$id'
    | '/api/documents/preview-bbbee'
    | '/api/documents/upload'
    | '/api/eft/bank-details'
    | '/api/eft/my-requests'
    | '/api/eft/request'
    | '/api/reference/bargaining-councils'
    | '/api/referrals/lookup'
    | '/api/referrals/my'
    | '/api/reminders/sweep'
    | '/api/tender/$tenderId'
    | '/api/tenders/$companyId'
    | '/api/tenders/analyze'
    | '/api/verify/statutory'
    | '/api/companies'
    | '/api/admin/companies/$companyId'
    | '/api/admin/impersonate/$userId'
    | '/api/admin/users/$userId'
    | '/api/billing/credits/$companyId'
    | '/api/documents/company/$companyId'
    | '/api/documents/download/$docId'
    | '/api/eft/admin/all'
    | '/api/eft/request/$paymentId'
    | '/api/eft/upload-proof/$paymentId'
    | '/api/reminders/test/$companyId'
    | '/api/tender/$tenderId/sbd4'
    | '/api/tender/$tenderId/sbd61'
    | '/api/tenders/download/$tenderId'
    | '/api/eft/admin/$paymentId/confirm'
    | '/api/eft/admin/$paymentId/reject'
    | '/api/eft/admin/proof/$paymentId'
    | '/api/tender/$tenderId/returnables/toggle'
    | '/api/tender/$tenderId/returnables/upload'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/admin'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authed/analyze'
    | '/_authed/app'
    | '/_authed/billing'
    | '/_authed/documents'
    | '/_authed/help'
    | '/_authed/setup'
    | '/admin/companies'
    | '/admin/eft'
    | '/admin/help'
    | '/admin/users'
    | '/admin/'
    | '/api/admin/companies'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/billing/packages'
    | '/api/companies/$companyId'
    | '/api/dashboard/activity'
    | '/api/documents/$id'
    | '/api/documents/preview-bbbee'
    | '/api/documents/upload'
    | '/api/eft/bank-details'
    | '/api/eft/my-requests'
    | '/api/eft/request'
    | '/api/reference/bargaining-councils'
    | '/api/referrals/lookup'
    | '/api/referrals/my'
    | '/api/reminders/sweep'
    | '/api/tender/$tenderId'
    | '/api/tenders/$companyId'
    | '/api/tenders/analyze'
    | '/api/verify/statutory'
    | '/api/companies/'
    | '/api/admin/companies/$companyId'
    | '/api/admin/impersonate/$userId'
    | '/api/admin/users/$userId'
    | '/api/billing/credits/$companyId'
    | '/api/documents/company/$companyId'
    | '/api/documents/download/$docId'
    | '/api/eft/admin/all'
    | '/api/eft/request/$paymentId'
    | '/api/eft/upload-proof/$paymentId'
    | '/api/reminders/test/$companyId'
    | '/api/tender/$tenderId/sbd4'
    | '/api/tender/$tenderId/sbd61'
    | '/api/tenders/download/$tenderId'
    | '/api/eft/admin/$paymentId/confirm'
    | '/api/eft/admin/$paymentId/reject'
    | '/api/eft/admin/proof/$paymentId'
    | '/api/tender/$tenderId/returnables/toggle'
    | '/api/tender/$tenderId/returnables/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiAdminCompaniesRoute: typeof ApiAdminCompaniesRouteWithChildren
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingPackagesRoute: typeof ApiBillingPackagesRoute
  ApiCompaniesCompanyIdRoute: typeof ApiCompaniesCompanyIdRoute
  ApiDashboardActivityRoute: typeof ApiDashboardActivityRoute
  ApiDocumentsIdRoute: typeof ApiDocumentsIdRoute
  ApiDocumentsPreviewBbbeeRoute: typeof ApiDocumentsPreviewBbbeeRoute
  ApiDocumentsUploadRoute: typeof ApiDocumentsUploadRoute
  ApiEftBankDetailsRoute: typeof ApiEftBankDetailsRoute
  ApiEftMyRequestsRoute: typeof ApiEftMyRequestsRoute
  ApiEftRequestRoute: typeof ApiEftRequestRouteWithChildren
  ApiReferenceBargainingCouncilsRoute: typeof ApiReferenceBargainingCouncilsRoute
  ApiReferralsLookupRoute: typeof ApiReferralsLookupRoute
  ApiReferralsMyRoute: typeof ApiReferralsMyRoute
  ApiRemindersSweepRoute: typeof ApiRemindersSweepRoute
  ApiTenderTenderIdRoute: typeof ApiTenderTenderIdRouteWithChildren
  ApiTendersCompanyIdRoute: typeof ApiTendersCompanyIdRoute
  ApiTendersAnalyzeRoute: typeof ApiTendersAnalyzeRoute
  ApiVerifyStatutoryRoute: typeof ApiVerifyStatutoryRoute
  ApiCompaniesIndexRoute: typeof ApiCompaniesIndexRoute
  ApiAdminImpersonateUserIdRoute: typeof ApiAdminImpersonateUserIdRoute
  ApiBillingCreditsCompanyIdRoute: typeof ApiBillingCreditsCompanyIdRoute
  ApiDocumentsCompanyCompanyIdRoute: typeof ApiDocumentsCompanyCompanyIdRoute
  ApiDocumentsDownloadDocIdRoute: typeof ApiDocumentsDownloadDocIdRoute
  ApiEftAdminAllRoute: typeof ApiEftAdminAllRoute
  ApiEftUploadProofPaymentIdRoute: typeof ApiEftUploadProofPaymentIdRoute
  ApiRemindersTestCompanyIdRoute: typeof ApiRemindersTestCompanyIdRoute
  ApiTendersDownloadTenderIdRoute: typeof ApiTendersDownloadTenderIdRoute
  ApiEftAdminPaymentIdConfirmRoute: typeof ApiEftAdminPaymentIdConfirmRoute
  ApiEftAdminPaymentIdRejectRoute: typeof ApiEftAdminPaymentIdRejectRoute
  ApiEftAdminProofPaymentIdRoute: typeof ApiEftAdminProofPaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/analyze': {
      id: '/_authed/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthedAnalyzeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/documents': {
      id: '/_authed/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthedDocumentsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/help': {
      id: '/_authed/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthedHelpRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/eft': {
      id: '/admin/eft'
      path: '/eft'
      fullPath: '/admin/eft'
      preLoaderRoute: typeof AdminEftRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/admin/companies': {
      id: '/api/admin/companies'
      path: '/api/admin/companies'
      fullPath: '/api/admin/companies'
      preLoaderRoute: typeof ApiAdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/packages': {
      id: '/api/billing/packages'
      path: '/api/billing/packages'
      fullPath: '/api/billing/packages'
      preLoaderRoute: typeof ApiBillingPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies/': {
      id: '/api/companies/'
      path: '/api/companies'
      fullPath: '/api/companies/'
      preLoaderRoute: typeof ApiCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies/$companyId': {
      id: '/api/companies/$companyId'
      path: '/api/companies/$companyId'
      fullPath: '/api/companies/$companyId'
      preLoaderRoute: typeof ApiCompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/activity': {
      id: '/api/dashboard/activity'
      path: '/api/dashboard/activity'
      fullPath: '/api/dashboard/activity'
      preLoaderRoute: typeof ApiDashboardActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id': {
      id: '/api/documents/$id'
      path: '/api/documents/$id'
      fullPath: '/api/documents/$id'
      preLoaderRoute: typeof ApiDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/preview-bbbee': {
      id: '/api/documents/preview-bbbee'
      path: '/api/documents/preview-bbbee'
      fullPath: '/api/documents/preview-bbbee'
      preLoaderRoute: typeof ApiDocumentsPreviewBbbeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/upload': {
      id: '/api/documents/upload'
      path: '/api/documents/upload'
      fullPath: '/api/documents/upload'
      preLoaderRoute: typeof ApiDocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eft/bank-details': {
      id: '/api/eft/bank-details'
      path: '/api/eft/bank-details'
      fullPath: '/api/eft/bank-details'
      preLoaderRoute: typeof ApiEftBankDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eft/my-requests': {
      id: '/api/eft/my-requests'
      path: '/api/eft/my-requests'
      fullPath: '/api/eft/my-requests'
      preLoaderRoute: typeof ApiEftMyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eft/request': {
      id: '/api/eft/request'
      path: '/api/eft/request'
      fullPath: '/api/eft/request'
      preLoaderRoute: typeof ApiEftRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reference/bargaining-councils': {
      id: '/api/reference/bargaining-councils'
      path: '/api/reference/bargaining-councils'
      fullPath: '/api/reference/bargaining-councils'
      preLoaderRoute: typeof ApiReferenceBargainingCouncilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals/lookup': {
      id: '/api/referrals/lookup'
      path: '/api/referrals/lookup'
      fullPath: '/api/referrals/lookup'
      preLoaderRoute: typeof ApiReferralsLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals/my': {
      id: '/api/referrals/my'
      path: '/api/referrals/my'
      fullPath: '/api/referrals/my'
      preLoaderRoute: typeof ApiReferralsMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders/sweep': {
      id: '/api/reminders/sweep'
      path: '/api/reminders/sweep'
      fullPath: '/api/reminders/sweep'
      preLoaderRoute: typeof ApiRemindersSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tender/$tenderId': {
      id: '/api/tender/$tenderId'
      path: '/api/tender/$tenderId'
      fullPath: '/api/tender/$tenderId'
      preLoaderRoute: typeof ApiTenderTenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenders/$companyId': {
      id: '/api/tenders/$companyId'
      path: '/api/tenders/$companyId'
      fullPath: '/api/tenders/$companyId'
      preLoaderRoute: typeof ApiTendersCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenders/analyze': {
      id: '/api/tenders/analyze'
      path: '/api/tenders/analyze'
      fullPath: '/api/tenders/analyze'
      preLoaderRoute: typeof ApiTendersAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify/statutory': {
      id: '/api/verify/statutory'
      path: '/api/verify/statutory'
      fullPath: '/api/verify/statutory'
      preLoaderRoute: typeof ApiVerifyStatutoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/companies/$companyId': {
      id: '/api/admin/companies/$companyId'
      path: '/$companyId'
      fullPath: '/api/admin/companies/$companyId'
      preLoaderRoute: typeof ApiAdminCompaniesCompanyIdRouteImport
      parentRoute: typeof ApiAdminCompaniesRoute
    }
    '/api/admin/impersonate/$userId': {
      id: '/api/admin/impersonate/$userId'
      path: '/api/admin/impersonate/$userId'
      fullPath: '/api/admin/impersonate/$userId'
      preLoaderRoute: typeof ApiAdminImpersonateUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/billing/credits/$companyId': {
      id: '/api/billing/credits/$companyId'
      path: '/api/billing/credits/$companyId'
      fullPath: '/api/billing/credits/$companyId'
      preLoaderRoute: typeof ApiBillingCreditsCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/company/$companyId': {
      id: '/api/documents/company/$companyId'
      path: '/api/documents/company/$companyId'
      fullPath: '/api/documents/company/$companyId'
      preLoaderRoute: typeof ApiDocumentsCompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/download/$docId': {
      id: '/api/documents/download/$docId'
      path: '/api/documents/download/$docId'
      fullPath: '/api/documents/download/$docId'
      preLoaderRoute: typeof ApiDocumentsDownloadDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eft/admin/all': {
      id: '/api/eft/admin/all'
      path: '/api/eft/admin/all'
      fullPath: '/api/eft/admin/all'
      preLoaderRoute: typeof ApiEftAdminAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eft/request/$paymentId': {
      id: '/api/eft/request/$paymentId'
      path: '/$paymentId'
      fullPath: '/api/eft/request/$paymentId'
      preLoaderRoute: typeof ApiEftRequestPaymentIdRouteImport
      parentRoute: typeof ApiEftRequestRoute
    }
    '/api/eft/upload-proof/$paymentId': {
      id: '/api/eft/upload-proof/$paymentId'
      path: '/api/eft/upload-proof/$paymentId'
      fullPath: '/api/eft/upload-proof/$paymentId'
      preLoaderRoute: typeof ApiEftUploadProofPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders/test/$companyId': {
      id: '/api/reminders/test/$companyId'
      path: '/api/reminders/test/$companyId'
      fullPath: '/api/reminders/test/$companyId'
      preLoaderRoute: typeof ApiRemindersTestCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tender/$tenderId/sbd4': {
      id: '/api/tender/$tenderId/sbd4'
      path: '/sbd4'
      fullPath: '/api/tender/$tenderId/sbd4'
      preLoaderRoute: typeof ApiTenderTenderIdSbd4RouteImport
      parentRoute: typeof ApiTenderTenderIdRoute
    }
    '/api/tender/$tenderId/sbd61': {
      id: '/api/tender/$tenderId/sbd61'
      path: '/sbd61'
      fullPath: '/api/tender/$tenderId/sbd61'
      preLoaderRoute: typeof ApiTenderTenderIdSbd61RouteImport
      parentRoute: typeof ApiTenderTenderIdRoute
    }
    '/api/tenders/download/$tenderId': {
      id: '/api/tenders/download/$tenderId'
      path: '/api/tenders/download/$tenderId'
      fullPath: '/api/tenders/download/$tenderId'
      preLoaderRoute: typeof ApiTendersDownloadTenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eft/admin/$paymentId/confirm': {
      id: '/api/eft/admin/$paymentId/confirm'
      path: '/api/eft/admin/$paymentId/confirm'
      fullPath: '/api/eft/admin/$paymentId/confirm'
      preLoaderRoute: typeof ApiEftAdminPaymentIdConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eft/admin/$paymentId/reject': {
      id: '/api/eft/admin/$paymentId/reject'
      path: '/api/eft/admin/$paymentId/reject'
      fullPath: '/api/eft/admin/$paymentId/reject'
      preLoaderRoute: typeof ApiEftAdminPaymentIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eft/admin/proof/$paymentId': {
      id: '/api/eft/admin/proof/$paymentId'
      path: '/api/eft/admin/proof/$paymentId'
      fullPath: '/api/eft/admin/proof/$paymentId'
      preLoaderRoute: typeof ApiEftAdminProofPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tender/$tenderId/returnables/toggle': {
      id: '/api/tender/$tenderId/returnables/toggle'
      path: '/returnables/toggle'
      fullPath: '/api/tender/$tenderId/returnables/toggle'
      preLoaderRoute: typeof ApiTenderTenderIdReturnablesToggleRouteImport
      parentRoute: typeof ApiTenderTenderIdRoute
    }
    '/api/tender/$tenderId/returnables/upload': {
      id: '/api/tender/$tenderId/returnables/upload'
      path: '/returnables/upload'
      fullPath: '/api/tender/$tenderId/returnables/upload'
      preLoaderRoute: typeof ApiTenderTenderIdReturnablesUploadRouteImport
      parentRoute: typeof ApiTenderTenderIdRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAnalyzeRoute: typeof AuthedAnalyzeRoute
  AuthedAppRoute: typeof AuthedAppRoute
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedDocumentsRoute: typeof AuthedDocumentsRoute
  AuthedHelpRoute: typeof AuthedHelpRoute
  AuthedSetupRoute: typeof AuthedSetupRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAnalyzeRoute: AuthedAnalyzeRoute,
  AuthedAppRoute: AuthedAppRoute,
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedDocumentsRoute: AuthedDocumentsRoute,
  AuthedHelpRoute: AuthedHelpRoute,
  AuthedSetupRoute: AuthedSetupRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminEftRoute: typeof AdminEftRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminEftRoute: AdminEftRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiAdminCompaniesRouteChildren {
  ApiAdminCompaniesCompanyIdRoute: typeof ApiAdminCompaniesCompanyIdRoute
}

const ApiAdminCompaniesRouteChildren: ApiAdminCompaniesRouteChildren = {
  ApiAdminCompaniesCompanyIdRoute: ApiAdminCompaniesCompanyIdRoute,
}

const ApiAdminCompaniesRouteWithChildren =
  ApiAdminCompaniesRoute._addFileChildren(ApiAdminCompaniesRouteChildren)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiEftRequestRouteChildren {
  ApiEftRequestPaymentIdRoute: typeof ApiEftRequestPaymentIdRoute
}

const ApiEftRequestRouteChildren: ApiEftRequestRouteChildren = {
  ApiEftRequestPaymentIdRoute: ApiEftRequestPaymentIdRoute,
}

const ApiEftRequestRouteWithChildren = ApiEftRequestRoute._addFileChildren(
  ApiEftRequestRouteChildren,
)

interface ApiTenderTenderIdRouteChildren {
  ApiTenderTenderIdSbd4Route: typeof ApiTenderTenderIdSbd4Route
  ApiTenderTenderIdSbd61Route: typeof ApiTenderTenderIdSbd61Route
  ApiTenderTenderIdReturnablesToggleRoute: typeof ApiTenderTenderIdReturnablesToggleRoute
  ApiTenderTenderIdReturnablesUploadRoute: typeof ApiTenderTenderIdReturnablesUploadRoute
}

const ApiTenderTenderIdRouteChildren: ApiTenderTenderIdRouteChildren = {
  ApiTenderTenderIdSbd4Route: ApiTenderTenderIdSbd4Route,
  ApiTenderTenderIdSbd61Route: ApiTenderTenderIdSbd61Route,
  ApiTenderTenderIdReturnablesToggleRoute:
    ApiTenderTenderIdReturnablesToggleRoute,
  ApiTenderTenderIdReturnablesUploadRoute:
    ApiTenderTenderIdReturnablesUploadRoute,
}

const ApiTenderTenderIdRouteWithChildren =
  ApiTenderTenderIdRoute._addFileChildren(ApiTenderTenderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiAdminCompaniesRoute: ApiAdminCompaniesRouteWithChildren,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingPackagesRoute: ApiBillingPackagesRoute,
  ApiCompaniesCompanyIdRoute: ApiCompaniesCompanyIdRoute,
  ApiDashboardActivityRoute: ApiDashboardActivityRoute,
  ApiDocumentsIdRoute: ApiDocumentsIdRoute,
  ApiDocumentsPreviewBbbeeRoute: ApiDocumentsPreviewBbbeeRoute,
  ApiDocumentsUploadRoute: ApiDocumentsUploadRoute,
  ApiEftBankDetailsRoute: ApiEftBankDetailsRoute,
  ApiEftMyRequestsRoute: ApiEftMyRequestsRoute,
  ApiEftRequestRoute: ApiEftRequestRouteWithChildren,
  ApiReferenceBargainingCouncilsRoute: ApiReferenceBargainingCouncilsRoute,
  ApiReferralsLookupRoute: ApiReferralsLookupRoute,
  ApiReferralsMyRoute: ApiReferralsMyRoute,
  ApiRemindersSweepRoute: ApiRemindersSweepRoute,
  ApiTenderTenderIdRoute: ApiTenderTenderIdRouteWithChildren,
  ApiTendersCompanyIdRoute: ApiTendersCompanyIdRoute,
  ApiTendersAnalyzeRoute: ApiTendersAnalyzeRoute,
  ApiVerifyStatutoryRoute: ApiVerifyStatutoryRoute,
  ApiCompaniesIndexRoute: ApiCompaniesIndexRoute,
  ApiAdminImpersonateUserIdRoute: ApiAdminImpersonateUserIdRoute,
  ApiBillingCreditsCompanyIdRoute: ApiBillingCreditsCompanyIdRoute,
  ApiDocumentsCompanyCompanyIdRoute: ApiDocumentsCompanyCompanyIdRoute,
  ApiDocumentsDownloadDocIdRoute: ApiDocumentsDownloadDocIdRoute,
  ApiEftAdminAllRoute: ApiEftAdminAllRoute,
  ApiEftUploadProofPaymentIdRoute: ApiEftUploadProofPaymentIdRoute,
  ApiRemindersTestCompanyIdRoute: ApiRemindersTestCompanyIdRoute,
  ApiTendersDownloadTenderIdRoute: ApiTendersDownloadTenderIdRoute,
  ApiEftAdminPaymentIdConfirmRoute: ApiEftAdminPaymentIdConfirmRoute,
  ApiEftAdminPaymentIdRejectRoute: ApiEftAdminPaymentIdRejectRoute,
  ApiEftAdminProofPaymentIdRoute: ApiEftAdminProofPaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
